[package]
name = "ZoomBotC2"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
reqwest = { version = "0.11", features = ["blocking","json"] }
tokio = { version = "1.15", features = ["full"] }
